### ISSUE TITLE
LlamaForCausalLM requires the PyTorch library but it was not found in your environment

### ISSUE THREAD

**Issue by 459737087** [LargeWorldModel/LWM#49]
```
Traceback (most recent call last):
  File "/output/LWM/scripts/sample_pyt.py", line 8, in <module>
    model = LlamaForCausalLM.from_pretrained(args.model)
  File "/usr/local/envs/lwm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1112, in __getattribute__
    requires_backends(cls, cls._backends)
  File "/usr/local/envs/lwm/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1100, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
LlamaForCausalLM requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.
```

**Comment by 459737087** [comment]
separately install torch
